import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Modal Examples",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div
          id="root"
          className="container mx-auto p-4 text-5xl font-extrabold"
        >
          {children}
        </div>
        {modal}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
